01:
	ruby src/solution01.rb < ./input.txt
	@echo DONE

02:
	ruby src/solution02.rb < input.txt
	@echo DONE

01_t:
	ruby src/solution01.rb < ./input_test.txt
	@echo DONE

02_t:
	ruby src/solution02.rb < input_test.txt
	@echo DONE
